version: '3.8'

services:
  # TeamSpeak 3 Server pour les tests
  teamspeak3-server:
    image: teamspeak:latest
    container_name: ts3-test-server
    restart: unless-stopped
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_sqlite3
      TS3SERVER_DB_SQLCREATEPATH: create_sqlite
      TS3SERVER_DB_HOST: ""
      TS3SERVER_DB_USER: ""
      TS3SERVER_DB_PASSWORD: ""
      TS3SERVER_DB_NAME: ""
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
      # Configuration pour les tests
      TS3SERVER_QUERY_PROTOCOLS: raw
      TS3SERVER_QUERY_TIMEOUT: 300
    ports:
      - "9987:9987/udp"   # TeamSpeak port
      - "10011:10011"     # ServerQuery port  
      - "30033:30033"     # File transfer port
    volumes:
      - ts3-test-data:/var/ts3server/
      - ts3-test-logs:/var/ts3server/logs/
    networks:
      - ts3-test-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "10011"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Service de test pour notre MCP
  teamspeak-mcp-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ts3-mcp-test
    depends_on:
      teamspeak3-server:
        condition: service_healthy
    environment:
      TEAMSPEAK_HOST: teamspeak3-server
      TEAMSPEAK_PORT: 10011
      TEAMSPEAK_USER: serveradmin
      TEAMSPEAK_PASSWORD: ""  # Will be set from TS3 server logs
      TEAMSPEAK_SERVER_ID: 1
      # Test configuration
      TEST_MODE: "true"
      LOG_LEVEL: DEBUG
    networks:
      - ts3-test-network
    volumes:
      - ./tests:/app/tests
      - ./test_results:/app/test_results
    command: ["test"]

  # Service pour extraire le token admin du serveur TS3
  token-extractor:
    image: alpine:latest
    container_name: ts3-token-extractor
    depends_on:
      teamspeak3-server:
        condition: service_healthy
    volumes:
      - ts3-test-logs:/ts3-logs:ro
      - ./scripts:/scripts
    networks:
      - ts3-test-network
    command: >
      sh -c "
        echo 'Extracting admin token from TS3 logs...';
        sleep 5;
        grep -r 'token=' /ts3-logs/ | head -1 | sed 's/.*token=\\([A-Za-z0-9+/=]*\\).*/\\1/' > /scripts/admin_token.txt;
        if [ -s /scripts/admin_token.txt ]; then
          echo 'Admin token extracted successfully';
          cat /scripts/admin_token.txt;
        else
          echo 'Failed to extract admin token';
          exit 1;
        fi
      "

volumes:
  ts3-test-data:
    driver: local
  ts3-test-logs:
    driver: local

networks:
  ts3-test-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 